default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: payjp_practice_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: payjp_practice_test

production:
  <<: *default
  adapter: postgresql
  database: payjp_practice_production
  username: payjp_practice
  password: <%= ENV["PAYJP_PRACTICE_DATABASE_PASSWORD"] %>